// <auto-generated />
using System;
using Flights.Orchestrator.Core.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flights.Orchestrator.Core.Migrations
{
    [DbContext(typeof(OrchestratorDbContext))]
    [Migration("20260702191413_RemoveUnusedPendingQuestionContextJson")]
    partial class RemoveUnusedPendingQuestionContextJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Flights.Orchestrator.Core.Models.BacklogTask", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AcceptanceCriteria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DependsOnTaskIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IterationCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastDeveloperSummaryJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastReviewerVerdictJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BacklogTasks");
                });

            modelBuilder.Entity("Flights.Orchestrator.Core.Models.IterationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BacklogTaskId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeveloperSummaryJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IterationNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewerVerdictJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacklogTaskId");

                    b.ToTable("IterationRecords");
                });

            modelBuilder.Entity("Flights.Orchestrator.Core.Models.PendingQuestion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AnswerText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("BacklogTaskId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Consumed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("PendingQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
